{% set name = "serpenttools" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad9348264d8ff763edb48267ca0b07557b92304168cfee5f5b018fb7d07303d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8,<3.12
    - numpy >=1.16.0
    - matplotlib-base >=2.2.3,!=3.3.4
    - pyyaml >=5.1.1

test:
  imports:
    - serpentTools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CORE-GATECH-GROUP/serpent-tools
  summary: A suite of parsers designed to make interacting with Serpent output files simple, scriptable, and flawless
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - drewejohnson
    - DanKotlyar
